apiVersion: v1
kind: Pod
metadata:
  name: fresco-nginx-pod
spec:
  volumes:
  - name: foo
    secret:
       secretName: fresco-secret
  - name: test-volume
    persistentVolumeClaim:
      claimName: fresco-pvc
  containers:
  - name: fresco-nginx-container
    image: nginx
    env:
      - name: SEVER_URL_ENV
        valueFrom:
            configMapKeyRef:
              name: fresco-config
              key: SERVER_URL
    volumeMounts:
    - name: foo
      readOnly: true
      mountPath: "/etc/test"
    - mountPath: /usr/share/nginx/html
      name: test-volume
